name: dart_achieve
description: Dart Language Learning.
version: 0.0.1+1
# homepage: https://www.example.com
# author: root <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
