name: dart_console_01
description: A sample command-line application.
version: 0.2.2
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
